/**
 * Installing the shell integration — three ways in, all of them reversible.
 *
 *   danger shell    a subshell with the plugin loaded. Changes nothing on disk.
 *   danger init     one line appended to ~/.zshrc. The normal install.
 *   danger init --login-shell   additionally prints the `chsh` recipe.
 *
 * WHY ZDOTDIR AND NOT A REAL SHELL BINARY. `chsh -s /path/to/danger` would make
 * danger the login shell, and then danger would have to *be* a shell: job
 * control, globbing, completion, `[[ ]]`, arrays, ~200 options. Nobody has
 * shipped a credible one in a decade of trying. Instead the `danger-shell` stub
 * execs the user's real zsh with ZDOTDIR pointed at a directory of forwarding
 * stubs, so the login shell genuinely is zsh — same binary, same version, same
 * rc files, and the plugin loaded after all of them.
 *
 * The forwarding matters and is easy to get wrong. zsh reads, in order:
 * `$ZDOTDIR/.zshenv`, then `.zprofile` (login), `.zshrc` (interactive),
 * `.zlogin` (login). Point ZDOTDIR somewhere new and *all four* stop being read
 * from the user's home, which silently drops their PATH, their prompt and their
 * framework. So every one of them gets a stub that sources the real file.
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync, chmodSync } from "node:fs";
import { homedir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { execFileSync, spawnSync } from "node:child_process";
import { emitZshRules } from "./rules.js";
import { underDir } from "../config.js";

const MARKER_START = "# >>> danger shell integration >>>";
const MARKER_END = "# <<< danger shell integration <<<";

function shellDir(): string {
  return join(underDir(), "shell");
}

/** Locate `plugin.zsh`, which ships as an asset beside the compiled output. */
function pluginSource(): string | null {
  const here = dirname(fileURLToPath(import.meta.url));
  for (const c of [
    join(here, "plugin.zsh"), // dist/shell/plugin.zsh — copied by the build
    join(here, "..", "..", "src", "shell", "plugin.zsh"), // running from dist, source present
    join(here, "..", "src", "shell", "plugin.zsh"),
  ]) {
    if (existsSync(c)) return c;
  }
  return null;
}

/**
 * Write the plugin and its generated rule table into ~/.underclass/shell.
 *
 * Copied rather than sourced in place so an npm upgrade cannot change the code
 * your shell runs at startup without you re-running `danger init` — a package
 * update that silently rewrites everyone's shell hooks is how a convenience
 * becomes an incident.
 */
export function stageAssets(): { plugin: string; rules: string } {
  const dir = shellDir();
  mkdirSync(dir, { recursive: true, mode: 0o700 });

  const src = pluginSource();
  if (!src) throw new Error("cannot find plugin.zsh — the install is incomplete, try reinstalling underclass");
  const plugin = join(dir, "danger.plugin.zsh");
  writeFileSync(plugin, readFileSync(src, "utf8"), { mode: 0o600 });

  const rules = join(dir, "danger-rules.zsh");
  writeFileSync(rules, emitZshRules(), { mode: 0o600 });
  stageBinShim();
  return { plugin, rules };
}

/**
 * Put `danger` on PATH as a real command.
 *
 * Everything model-backed in the plugin shells out to `command danger` — Tab on
 * prose, `danger why`, `danger edit`. If the binary is not on PATH, all of it
 * silently dies and only the static heuristics survive, which is precisely the
 * shape of "it works almost like zsh but never explains anything".
 *
 * That is not hypothetical: `danger shell` launched a subshell whose greeting
 * says "`danger why` after a failure", in a shell where `danger` did not exist.
 * Anyone running from a checkout (`node …/dist/danger.js shell`) rather than a
 * global install hits it immediately.
 *
 * A shim rather than a PATH entry pointing into the package, because the entry
 * is a .js file that needs `node` in front of it, and because this pins the
 * interpreter that is actually running now.
 */
export function stageBinShim(): string {
  const dir = join(shellDir(), "bin");
  mkdirSync(dir, { recursive: true, mode: 0o700 });
  const entry = fileURLToPath(new URL("../danger.js", import.meta.url));
  const shim = join(dir, "danger");
  writeFileSync(
    shim,
    `#!/bin/sh\n# Generated by danger. Points at the install that created it.\nexec ${JSON.stringify(process.execPath)} ${JSON.stringify(entry)} "$@"\n`,
    { mode: 0o755 },
  );
  chmodSync(shim, 0o755);
  return dir;
}

/**
 * The ZDOTDIR forwarding directory, for the `chsh` path only.
 *
 * `$ZDOTDIR` is where the user's rc files were before we moved it, so the stubs
 * capture the original value and hand it back — which also means a shell
 * started with an already-custom ZDOTDIR (VS Code and Cursor both do this, see
 * DESIGN.md §3.5) keeps working instead of being redirected to $HOME.
 */
export function stageZdotdir(): string {
  const dir = join(shellDir(), "zdotdir");
  mkdirSync(dir, { recursive: true, mode: 0o700 });
  const plugin = join(shellDir(), "danger.plugin.zsh");

  // .zshenv runs for every zsh, including non-interactive ones, so it must do
  // nothing but forward. Anything else here would be inherited by every script.
  writeFileSync(
    join(dir, ".zshenv"),
    `# Generated by \`danger init --login-shell\`. Forwards to your real rc files.
# DANGER_REAL_ZDOTDIR is where zsh would have looked if danger were not here.
: \${DANGER_REAL_ZDOTDIR:=\${DANGER_PREV_ZDOTDIR:-$HOME}}
export DANGER_REAL_ZDOTDIR
[[ -r "$DANGER_REAL_ZDOTDIR/.zshenv" ]] && source "$DANGER_REAL_ZDOTDIR/.zshenv"
`,
    { mode: 0o600 },
  );

  for (const f of [".zprofile", ".zlogin", ".zlogout"]) {
    writeFileSync(
      join(dir, f),
      `[[ -r "\${DANGER_REAL_ZDOTDIR:-$HOME}/${f}" ]] && source "\${DANGER_REAL_ZDOTDIR:-$HOME}/${f}"\n`,
      { mode: 0o600 },
    );
  }

  // .zshrc sources the user's config FIRST and the plugin LAST, so we wrap
  // their Tab widget rather than having theirs overwrite ours — the ordering
  // bug that breaks completion for anyone running oh-my-zsh or fzf-tab.
  writeFileSync(
    join(dir, ".zshrc"),
    `[[ -r "\${DANGER_REAL_ZDOTDIR:-$HOME}/.zshrc" ]] && source "\${DANGER_REAL_ZDOTDIR:-$HOME}/.zshrc"
[[ -r "${plugin}" ]] && source "${plugin}"
`,
    { mode: 0o600 },
  );
  return dir;
}

/** The `chsh` target: a tiny exec stub, not a shell implementation. */
export function stageLoginStub(): string {
  const stub = join(shellDir(), "danger-shell");
  const zsh = whichZsh();
  writeFileSync(
    stub,
    `#!/bin/sh
# Generated by \`danger init --login-shell\`.
#
# This is not a shell. It execs your real zsh with ZDOTDIR pointed at danger's
# forwarding stubs, which source your own rc files and then the plugin. Your
# login shell remains ${zsh} — same binary, same version, same config.
#
# To undo:  chsh -s ${zsh}
DANGER_PREV_ZDOTDIR="\${ZDOTDIR:-$HOME}"
export DANGER_PREV_ZDOTDIR
ZDOTDIR="${join(shellDir(), "zdotdir")}"
export ZDOTDIR

# A login shell is marked by a leading "-" in argv[0], which /bin/sh cannot
# propagate through exec. Without re-adding it, zsh starts NON-login: it skips
# .zprofile and .zlogin entirely. That does not crash — it silently drops
# whatever those files set, which on macOS is typically \`brew shellenv\` (and
# here, OrbStack). Every new terminal would just be missing brew, docker and orb
# from PATH, with nothing to point at. Measured before this line existed:
# baseline \`-zsh\` gave options[login]=on and ran all four rc files; the stub
# gave .zprofile=NO, .zlogin=NO, login=off.
case "$0" in
  -*) exec "${zsh}" -l "$@" ;;
  *)  exec "${zsh}" "$@" ;;
esac
`,
    { mode: 0o755 },
  );
  chmodSync(stub, 0o755);
  return stub;
}

function whichZsh(): string {
  for (const c of [process.env.SHELL, "/bin/zsh", "/usr/local/bin/zsh", "/opt/homebrew/bin/zsh"]) {
    if (c && c.endsWith("zsh") && existsSync(c)) return c;
  }
  try {
    return execFileSync("command", ["-v", "zsh"], { encoding: "utf8", shell: "/bin/sh" }).trim() || "/bin/zsh";
  } catch {
    return "/bin/zsh";
  }
}

function rcPath(): string {
  const zdot = process.env.ZDOTDIR;
  // Respect an existing ZDOTDIR, but not ours — installing into our own
  // forwarding stub would make the plugin source itself on every shell.
  if (zdot && !zdot.startsWith(shellDir())) return join(zdot, ".zshrc");
  return join(homedir(), ".zshrc");
}

export interface InitResult {
  rc: string;
  action: "added" | "already-present" | "updated";
  plugin: string;
  loginStub?: string;
}

/**
 * Append the source line to .zshrc, idempotently.
 *
 * Bracketed by markers so uninstall is an exact range delete rather than a
 * pattern match against a line the user may have edited.
 */
export function init(opts: { loginShell?: boolean } = {}): InitResult {
  const { plugin } = stageAssets();
  const rc = rcPath();
  const existing = existsSync(rc) ? readFileSync(rc, "utf8") : "";

  const block = [
    MARKER_START,
    `# Remove this block, or run \`danger uninstall-shell\`, to undo.`,
    `[[ -r "${plugin}" ]] && source "${plugin}"`,
    MARKER_END,
  ].join("\n");

  let action: InitResult["action"];
  if (existing.includes(MARKER_START)) {
    const before = existing;
    const next = existing.replace(
      new RegExp(`${escapeRe(MARKER_START)}[\\s\\S]*?${escapeRe(MARKER_END)}`),
      block,
    );
    action = next === before ? "already-present" : "updated";
    if (action === "updated") writeFileSync(rc, next, "utf8");
  } else {
    // The plugin must come after the user's own config and after any framework,
    // so appending is correct — and is also why we do not offer to insert it
    // anywhere else.
    const sep = existing && !existing.endsWith("\n") ? "\n" : "";
    writeFileSync(rc, `${existing}${sep}\n${block}\n`, "utf8");
    action = "added";
  }

  const result: InitResult = { rc, action, plugin };
  if (opts.loginShell) {
    stageZdotdir();
    result.loginStub = stageLoginStub();
  }
  return result;
}

/** Remove the block. Leaves the staged files, which are inert without it. */
export function uninstall(): { rc: string; removed: boolean } {
  const rc = rcPath();
  if (!existsSync(rc)) return { rc, removed: false };
  const before = readFileSync(rc, "utf8");
  const after = before.replace(
    new RegExp(`\\n?${escapeRe(MARKER_START)}[\\s\\S]*?${escapeRe(MARKER_END)}\\n?`, "g"),
    "\n",
  );
  if (after === before) return { rc, removed: false };
  writeFileSync(rc, after, "utf8");
  return { rc, removed: true };
}

function escapeRe(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

/**
 * Start an interactive zsh with the plugin loaded and nothing installed.
 *
 * The try-before-you-commit path, and the one to recommend first: if the plugin
 * is going to fight someone's prompt theme or completion framework, they should
 * find that out in a subshell they can exit rather than in the shell they need
 * to get work done in.
 */
export function subshell(): number {
  stageAssets();
  const zdot = stageZdotdir();
  const zsh = whichZsh();
  const binDir = stageBinShim();
  // Inherited stdio, because an interactive shell needs the real terminal: a
  // piped one has no tty and therefore no ZLE, which is the feature being
  // demonstrated. `-i` without `-l` so we do not re-run login files.
  const r = spawnSync(zsh, ["-i"], {
    stdio: "inherit",
    env: {
      ...process.env,
      // Without this the subshell has no `danger`, so Tab-on-prose and
      // `danger why` both fail — while the greeting advertises both.
      PATH: `${binDir}:${process.env.PATH ?? ""}`,
      DANGER_PREV_ZDOTDIR: process.env.ZDOTDIR ?? homedir(),
      ZDOTDIR: zdot,
      DANGER_GREET: "1",
    },
  });
  return r.status ?? 1;
}
