use colored::Colorize;
use std::fs::{create_dir_all, read_to_string, set_permissions, write, Permissions};
use std::os::unix::fs::PermissionsExt;
use std::path::{Path, PathBuf};
use std::process::Command;
use crate::config::under_dir;
use crate::shell::rules::emit_zsh_rules;

pub const MARKER_START: &str = "# >>> danger shell integration >>>";
pub const MARKER_END: &str = "# <<< danger shell integration <<<";

pub fn shell_dir() -> PathBuf {
    under_dir().join("shell")
}

pub fn stage_assets() -> Result<(PathBuf, PathBuf), String> {
    let dir = shell_dir();
    create_dir_all(&dir).map_err(|e| e.to_string())?;

    let plugin_path = dir.join("danger.plugin.zsh");
    let plugin_content = include_str!("plugin.zsh");
    write(&plugin_path, plugin_content).map_err(|e| e.to_string())?;

    let rules_path = dir.join("danger-rules.zsh");
    let rules_content = emit_zsh_rules();
    write(&rules_path, rules_content).map_err(|e| e.to_string())?;

    stage_bin_shim()?;
    Ok((plugin_path, rules_path))
}

pub fn stage_bin_shim() -> Result<PathBuf, String> {
    let bin_dir = shell_dir().join("bin");
    create_dir_all(&bin_dir).map_err(|e| e.to_string())?;
    let shim = bin_dir.join("danger");

    let current_exe = std::env::current_exe().unwrap_or_else(|_| PathBuf::from("danger"));
    let shim_content = format!(
        "#!/bin/sh\n# Generated by danger. Points at the install that created it.\nexec {} \"$@\"\n",
        current_exe.display()
    );
    write(&shim, shim_content).map_err(|e| e.to_string())?;
    set_permissions(&shim, Permissions::from_mode(0o755)).map_err(|e| e.to_string())?;

    Ok(bin_dir)
}

pub fn stage_zdotdir() -> Result<PathBuf, String> {
    let zdot_dir = shell_dir().join("zdotdir");
    create_dir_all(&zdot_dir).map_err(|e| e.to_string())?;
    let plugin = shell_dir().join("danger.plugin.zsh");
    let home = dirs::home_dir().unwrap_or_else(|| PathBuf::from("."));

    write(
        zdot_dir.join(".zshenv"),
        "# Generated by danger init --login-shell. Forwards to your real rc files.\n\
         : ${DANGER_REAL_ZDOTDIR:=${DANGER_PREV_ZDOTDIR:-$HOME}}\n\
         export DANGER_REAL_ZDOTDIR\n\
         [[ -r \"$DANGER_REAL_ZDOTDIR/.zshenv\" ]] && source \"$DANGER_REAL_ZDOTDIR/.zshenv\"\n",
    ).map_err(|e| e.to_string())?;

    for f in [".zprofile", ".zlogin", ".zlogout"] {
        write(
            zdot_dir.join(f),
            format!("[[ -r \"${{DANGER_REAL_ZDOTDIR:-$HOME}}/{f}\" ]] && source \"${{DANGER_REAL_ZDOTDIR:-$HOME}}/{f}\"\n"),
        ).map_err(|e| e.to_string())?;
    }

    write(
        zdot_dir.join(".zshrc"),
        format!(
            "[[ -r \"${{DANGER_REAL_ZDOTDIR:-$HOME}}/.zshrc\" ]] && source \"${{DANGER_REAL_ZDOTDIR:-$HOME}}/.zshrc\"\n\
             [[ -r \"{}\" ]] && source \"{}\"\n",
            plugin.display(), plugin.display()
        ),
    ).map_err(|e| e.to_string())?;

    Ok(zdot_dir)
}

pub fn stage_login_stub() -> Result<PathBuf, String> {
    let stub = shell_dir().join("danger-shell");
    let zsh_path = which_zsh();
    let zdot = shell_dir().join("zdotdir");

    let content = format!(
        "#!/bin/sh\n\
         DANGER_PREV_ZDOTDIR=\"${{ZDOTDIR:-$HOME}}\"\n\
         export DANGER_PREV_ZDOTDIR\n\
         ZDOTDIR=\"{}\"\n\
         export ZDOTDIR\n\
         case \"$0\" in\n\
           -*) exec \"{}\" -l \"$@\" ;;\n\
           *)  exec \"{}\" \"$@\" ;;\n\
         esac\n",
        zdot.display(),
        zsh_path,
        zsh_path
    );

    write(&stub, content).map_err(|e| e.to_string())?;
    set_permissions(&stub, Permissions::from_mode(0o755)).map_err(|e| e.to_string())?;
    Ok(stub)
}

fn which_zsh() -> String {
    for c in ["/bin/zsh", "/usr/bin/zsh", "/usr/local/bin/zsh", "/opt/homebrew/bin/zsh"] {
        if Path::new(c).exists() {
            return c.to_string();
        }
    }
    "zsh".to_string()
}

pub fn install_zsh_plugin(login_shell: bool) -> Result<(), String> {
    let (plugin_path, _) = stage_assets()?;
    let home = dirs::home_dir().ok_or_else(|| "Cannot locate home directory".to_string())?;
    let zshrc = home.join(".zshrc");
    let existing = read_to_string(&zshrc).unwrap_or_default();

    let block = format!(
        "{MARKER_START}\n# Remove this block, or run `danger uninstall-shell`, to undo.\n[[ -r \"{}\" ]] && source \"{}\"\n{MARKER_END}",
        plugin_path.display(), plugin_path.display()
    );

    if existing.contains(MARKER_START) {
        let re = regex::Regex::new(&format!("{}[\\s\\S]*?{}", regex::escape(MARKER_START), regex::escape(MARKER_END))).unwrap();
        let updated = re.replace(&existing, block.as_str()).to_string();
        write(&zshrc, updated).map_err(|e| e.to_string())?;
        println!("{}", format!("danger: updated the integration in {}", zshrc.display()).yellow());
    } else {
        let sep = if existing.is_empty() || existing.ends_with('\n') { "" } else { "\n" };
        let new_content = format!("{existing}{sep}\n{block}\n");
        write(&zshrc, new_content).map_err(|e| e.to_string())?;
        println!("{}", format!("danger: added the integration to {}", zshrc.display()).green());
    }

    if login_shell {
        stage_zdotdir()?;
        let login_stub = stage_login_stub()?;
        println!("\n  To make it your login shell:\n    sudo sh -c 'echo {} >> /etc/shells'\n    chsh -s {}", login_stub.display(), login_stub.display());
    }

    println!("\nOpen a new shell or run: {}", "source ~/.zshrc".cyan().bold());
    Ok(())
}

pub fn uninstall_zsh_plugin() -> Result<(), String> {
    let home = dirs::home_dir().ok_or_else(|| "Cannot locate home directory".to_string())?;
    let zshrc = home.join(".zshrc");
    if zshrc.exists() {
        let content = read_to_string(&zshrc).unwrap_or_default();
        let re = regex::Regex::new(&format!("\\n?{}[\\s\\S]*?{}\\n?", regex::escape(MARKER_START), regex::escape(MARKER_END))).unwrap();
        let cleaned = re.replace_all(&content, "\n").to_string();
        write(&zshrc, cleaned).map_err(|e| e.to_string())?;
        println!("{}", format!("danger: removed integration from {}", zshrc.display()).green());
    }
    Ok(())
}

pub fn start_subshell() -> i32 {
    let _ = stage_assets();
    let zdot = stage_zdotdir().unwrap_or_else(|_| shell_dir().join("zdotdir"));
    let bin_dir = stage_bin_shim().unwrap_or_else(|_| shell_dir().join("bin"));
    let zsh_path = which_zsh();

    let current_path = std::env::var("PATH").unwrap_or_default();
    let new_path = format!("{}:{}", bin_dir.display(), current_path);
    let prev_zdot = std::env::var("ZDOTDIR").unwrap_or_else(|_| dirs::home_dir().unwrap_or_default().display().to_string());

    println!("{}", "danger shell — interactive subshell with danger integration loaded.".cyan().bold());
    println!("Type a description and press Tab to complete. Exit any time with `exit`.\n");

    let status = Command::new(&zsh_path)
        .arg("-i")
        .env("PATH", new_path)
        .env("DANGER_PREV_ZDOTDIR", prev_zdot)
        .env("ZDOTDIR", zdot)
        .env("DANGER_GREET", "1")
        .status();

    match status {
        Ok(s) => s.code().unwrap_or(0),
        Err(e) => {
            eprintln!("Failed to spawn subshell {zsh_path}: {e}");
            1
        }
    }
}
