use serde::{Deserialize, Serialize};
use std::path::{Path, PathBuf};
use std::process::Command;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FanOutTask {
    pub branch: String,
    pub prompt: String,
    pub message: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FanOutReport {
    pub branch: String,
    pub success: bool,
    pub error: Option<String>,
    pub pr_url: Option<String>,
}

pub fn create_worktree(base_branch: &str, task_branch: &str, cwd: &Path) -> Result<PathBuf, String> {
    let worktree_dir = cwd.join(".underclass").join("worktrees").join(task_branch);
    let _ = std::fs::create_dir_all(worktree_dir.parent().unwrap());

    let out = Command::new("git")
        .arg("worktree")
        .arg("add")
        .arg("-b")
        .arg(task_branch)
        .arg(&worktree_dir)
        .arg(base_branch)
        .current_dir(cwd)
        .output()
        .map_err(|e| format!("Failed to run git worktree add: {e}"))?;

    if !out.status.success() {
        let err = String::from_utf8_lossy(&out.stderr);
        return Err(format!("git worktree add failed: {err}"));
    }

    Ok(worktree_dir)
}

pub fn commit_and_clean_worktree(
    task_branch: &str,
    target_branch: &str,
    worktree_dir: &Path,
    cwd: &Path,
    no_merge: bool,
    create_pr: bool,
) -> FanOutReport {
    // 1. Git add & commit
    let _ = Command::new("git").arg("add").arg("-A").current_dir(worktree_dir).output();
    let commit_res = Command::new("git")
        .arg("commit")
        .arg("-m")
        .arg(format!("under fan-out: {task_branch}"))
        .current_dir(worktree_dir)
        .output();

    let mut pr_url = None;

    if create_pr {
        let _ = Command::new("git").arg("push").arg("-u").arg("origin").arg(task_branch).current_dir(worktree_dir).output();
        let gh_out = Command::new("gh")
            .arg("pr")
            .arg("create")
            .arg("--base")
            .arg(target_branch)
            .arg("--head")
            .arg(task_branch)
            .arg("--title")
            .arg(format!("under fan-out: {task_branch}"))
            .arg("--body")
            .arg("Automated fan-out PR generated by Underclass")
            .current_dir(worktree_dir)
            .output();

        if let Ok(out) = gh_out {
            if out.status.success() {
                pr_url = Some(String::from_utf8_lossy(&out.stdout).trim().to_string());
            }
        }
    } else if !no_merge {
        // Merge into target
        let _ = Command::new("git").arg("checkout").arg(target_branch).current_dir(cwd).output();
        let merge_out = Command::new("git").arg("merge").arg(task_branch).current_dir(cwd).output();
        if let Ok(m) = merge_out {
            if !m.status.success() {
                return FanOutReport {
                    branch: task_branch.to_string(),
                    success: false,
                    error: Some("Merge conflict on target branch".to_string()),
                    pr_url: None,
                };
            }
        }
    }

    // Clean up worktree
    let _ = Command::new("git")
        .arg("worktree")
        .arg("remove")
        .arg("--force")
        .arg(worktree_dir)
        .current_dir(cwd)
        .output();

    FanOutReport {
        branch: task_branch.to_string(),
        success: true,
        error: None,
        pr_url,
    }
}
